name: Angular Build and Online Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.19

      - name: Navigate to Angular Project Folder
        run: cd autoca-live-divingsum-main
        shell: bash

      - name: Install Dependencies (Sync Lock File)
        working-directory: autoca-live-divingsum-main
        run: npm install

      - name: Build Angular Application
        working-directory: autoca-live-divingsum-main
        run: npm run build

      - name: Run Online Linter (Conceptual)
        working-directory: autoca-live-divingsum-main
        run: |
          ONLINE_LINTER_API_URL="https://api.example-online-linter.com/lint" # Replace with a real API URL

          # Find all .js and .ts files
          find . -name "*.js" -o -name "*.ts" -print0 | while IFS= read -r -d $'\0' file; do
            echo "Linting $file online..."
            CODE=$(cat "$file")

            # Construct the data payload for the API (adjust as needed)
            PAYLOAD=$(jq -n --arg code "$CODE" '{ code: $code, language: "javascript" }') # Example JSON payload

            # Make the API request using curl
            RESPONSE=$(curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" "$ONLINE_LINTER_API_URL")

            echo "Online Linter Response for $file:"
            echo "$RESPONSE"

            # --- Error Parsing Logic (ADJUST BASED ON API RESPONSE FORMAT) ---
            if echo "$RESPONSE" | jq -e '.errorCount > 0'; then
              echo "Linting errors found in $file. Failing workflow."
              exit 1
            fi
            # --- End Error Parsing Logic ---
          done
        shell: bash
