name: Angular Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Navigate to Angular Project Folder
        run: cd autoca-live-divingsum-main
        shell: bash

      - name: Install Dependencies (Clean Install)
        working-directory: autoca-live-divingsum-main
        run: npm ci

      - name: Run ESLint
        working-directory: autoca-live-divingsum-main
        run: npm run lint

      - name: Run Stylelint (if configured)
        working-directory: autoca-live-divingsum-main
        run: npm run lint:styles || true

      # Optional: Check Formatting with Prettier
      # - name: Check Formatting with Prettier
      #   working-directory: autoca-live-divingsum-main
      #   run: npm run format:check || true

      # Optional: Fix ESLint Issues (use with caution on PRs)
      # - name: Fix ESLint Issues
      #   working-directory: autoca-live-divingsum-main
      #   run: npm run lint:fix
