name: Angular Lint

on:
  push:
    branches: [main]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

     # - name: Navigate to project directory
       # run: cd ./src/app/views/theme/privacypolicy
      
      - name: Install dependencies
        run: npm install

      #- name: Run Angular Linter
        # ... (your linter execution step)
