name: Lint

on:
  push:
    branches: [ "main", "develop" ] # Trigger on pushes to these branches
  pull_request:
    branches: [ "main", "develop" ] # Trigger on pull requests targeting these branches
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  lint:
    runs-on: ubuntu-latest # Use a Linux-based runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checks out your repository under $GITHUB_WORKSPACE

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x' # Or your preferred Node.js version

      - name: Install dependencies
        run: npm ci # Use npm ci for faster and cleaner installs

      - name: Lint with ESLint
        run: npm run lint # Assuming you have a "lint" script in your package.json

      - name: Lint with Stylelint
        run: npm run lint:styles # Assuming you have a "lint:styles" script in your package.json
