name: Angular Build and Lint (Force CJS Config)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.19

      - name: Navigate to Angular Project Folder
        run: cd autoca-live-divingsum-main
        shell: bash

      - name: Install Dependencies (Clean and Specific - ESLint v8)
        working-directory: autoca-live-divingsum-main
        run: |
          rm -rf node_modules package-lock.json
          npm install eslint@8.57.0 # Revert to a specific ESLint 8.x version
          npm install @typescript-eslint/eslint-plugin@latest @typescript-eslint/parser@latest
          npm install @angular-eslint/eslint-plugin@latest @angular-eslint/eslint-plugin-template@latest @angular-eslint/template-parser@latest @angular-eslint/builder@latest @angular-eslint/schematics@latest
          npm install eslint-config-prettier@latest
          npm install

      - name: Create .eslintrc.js (Force CJS)
        working-directory: autoca-live-divingsum-main
        run: |
          echo "module.exports = {
            root: true,
            ignorePatterns: ['projects/'],
            overrides: [
              {
                files: ['*.ts'],
                extends: [
                  'eslint:recommended',
                  'plugin:@typescript-eslint/recommended-type-checked',
                  'plugin:@angular-eslint/recommended',
                  'plugin:@angular-eslint/template/process-inline-templates',
                ],
                parserOptions: {
                  project: ['./tsconfig.json', './tsconfig.app.json', './tsconfig.spec.json'],
                },
                rules: {
                  '@typescript-eslint/no-unused-vars': 'warn',
                  '@angular-eslint/directive-selector': [
                    'error',
                    {
                      type: 'attribute',
                      prefix: 'app',
                      style: 'camelCase',
                    },
                  ],
                  '@angular-eslint/component-selector': [
                    'error',
                    {
                      type: 'element',
                      prefix: 'app',
                      style: 'kebab-case',
                    },
                  ],
                },
              },
              {
                files: ['*.html'],
                extends: ['plugin:@angular-eslint/template/recommended'],
                rules: {},
              },
            ],
          };" > .eslintrc.js
          if [ -f ".eslintrc.mjs" ]; then
            rm .eslintrc.mjs
          fi

      - name: Run Linter (Force CJS Config)
        working-directory: autoca-live-divingsum-main
        run: npm run lint

      - name: Build Angular Application
        working-directory: autoca-live-divingsum-main
        run: npm run build
