name: Lint Angular Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use the latest version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' # Use a stable LTS version
          cache: 'npm'

      
      - name: List files (debug)
        run: ls -la

      - name: Install dependencies with fallback
        run: |
          if [ -f package-lock.json ]; then
            echo "Using npm ci"
            npm ci
          else
            echo "No lockfile found, using npm install"
            npm install
          fi

      - name: Run ESLint
        run: npm run lint
