name: Angular Build and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-lint:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.19

      - name: Navigate to Angular Project Folder
        run: cd autoca-live-divingsum-main
        shell: bash

      - name: Install Dependencies
        working-directory: autoca-live-divingsum-main
        run: npm ci

      - name: Run Linter
        working-directory: autoca-live-divingsum-main
        run: npm run lint

      - name: Build Angular Application
        working-directory: autoca-live-divingsum-main
        run: npm run build
