jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x' # As indicated in your error

      - name: Install Dependencies
        run: npm ci
        working-directory: ${{ github.workspace }}

      # Add your build steps here (e.g., ng build)
      - name: Build Angular App
        run: ng build --configuration=production
        working-directory: ${{ github.workspace }}

      # Add steps to deploy your build artifacts
